version: '3'
services:

  # database -- reachable on 2345
  glpostgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=BartjeZekers
      - POSTGRES_USER=rcdn
      - POSTGRES_DB=drinksihad
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 2345:2345

volumes:
  postgres:
